// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6.Models;

namespace Mission6.Migrations
{
    [DbContext(typeof(movieFormContext))]
    [Migration("20230211203419_test")]
    partial class test
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission6.Models.FormResponse", b =>
                {
                    b.Property<int>("AppID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("AppID");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            AppID = 1,
                            Category = "Comedy",
                            Director = "Idk but someone good probably",
                            Edited = true,
                            LentTo = "Faline",
                            Notes = "Quite good indeed",
                            Rating = "PG",
                            Title = "Fantastic Mr. Fox",
                            Year = 2009
                        },
                        new
                        {
                            AppID = 2,
                            Category = "Adventure",
                            Director = "Christopher Nolan",
                            Edited = true,
                            LentTo = "Your mother",
                            Notes = "WOWOWOWOWOW",
                            Rating = "PG-13",
                            Title = "Interstellar",
                            Year = 2014
                        },
                        new
                        {
                            AppID = 3,
                            Category = "Fantasy",
                            Director = "Hayao Miyazaki",
                            Edited = true,
                            LentTo = "My ex #rip",
                            Notes = "pretty dang good",
                            Rating = "PG",
                            Title = "Spirited Away",
                            Year = 2001
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
